### PR TITLE
Allow AAP to be non integer

### PR DESCRIPTION
**Pull request by RosCraddock**
Small updates to input the alt_allele_prob_file as a float rather than an integer (which is then turned into a float). This now allows the inputting of decimals such as 0.5, 0.45 which previously caused a valueError.

### CODE REVIEW

**Comment by RosCraddock** [comment]
Apologies, I forgot to tag. @gregorgorjanc and @XingerTang, please review when you can.

**Comment by gregorgorjanc** [comment]
@RosCraddock I don't think we need the `nonInteger` argument here - we just need to pass the `dtype` as a float and not as an integer. And `dtype` should likely be float by default anyhow as we work with probabilities in AlphaPeel. OK?

**Comment by XingerTang** [comment]
@gregorgorjanc Normally that function only takes sequence and genotype input so it is originally designed for the integer inputs.

**Comment by gregorgorjanc** [comment]
I see. Couldn't we then stick to `dtype` arg only (not adding the `nonInteger` arg) and if we pass in a `np.float` type then we avoid using the `int()` (as done in this PR)

**Comment by RosCraddock** [comment]
@gregorgorjanc you're right! I can make the conditional statement on line 67 using the dtype instead.

**Review by gregorgorjanc — APPROVED** [review]
LGTM!

**Pull request merged**
